version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    # Définir les variables d'environnement pour le test local
    environment:
      DB_HOST: db               # Point vers le service 'db' dans le compose network
      DB_NAME: mydb
      DB_USER: admin
      DB_PASSWORD: admin

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    # Pas besoin d'exposer 5432 si seul l'app web y accède
    # ports: 
    #   - "5432:5432"
